version: '3.8'

services:
  sitetack:
    build:
      context: .
      args:
        - PORT=${PORT}
    image: sitetack:latest
    container_name: sitetack_app
    ports:
      - "${PORT:-80}:${PORT:-80}"
    environment:
      - PORT=${PORT:-80}
    user: sitetack
