name: Black Linter
on: [pull_request]
jobs:
  linter_name:
    name: Black Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"