name: Push Docker Image to Google Artifact Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write  # Needed for Google authentication

jobs:
  push-to-gar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: nschloe/action-cached-lfs-checkout@v1

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.GCLOUD_WORKFLOW_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        access_token_lifetime: 300s
      id: auth

    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
             ${{ secrets.GCLOUD_GAR_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/sitetack/sitetack:${{ steps.get-tag.outputs.short_ref }}
             ${{ secrets.GCLOUD_GAR_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/sitetack/sitetack:latest