name: Push Docker Image to Google Artifact Registry

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write  # Needed for Google authentication

jobs:
  push-to-gar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: nschloe/action-cached-lfs-checkout@v1

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.GCLOUD_WORKFLOW_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        access_token_lifetime: 300s
      id: auth

    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.GCLOUD_GAR_REGION }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.GCLOUD_IMAGE }}

    - name: Push Docker Image to Google Artifact Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ secrets.GCLOUD_SERVICE_NAME }} \
          --image=${{ secrets.GCLOUD_IMAGE }}:latest \
          --region=${{ secrets.GCLOUD_GAR_REGION }} \
          --platform=managed \
          --allow-unauthenticated