name: Docker Build and Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: sitetack:latest
          outputs: type=docker,dest=/tmp/sitetack.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sitetack
          path: /tmp/sitetack.tar
  pytest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a     
      - name: Run Pytest in Docker Container
        run: docker run --rm sitetack:latest poetry run pytest

  pyright:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a     
      - name: Type test with pyright
        run: docker run --rm sitetack:latest poetry run pyright


