# name: Ruff
# on: [pull_request]
# jobs:
#   ruff:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Repository
#       uses: nschloe/action-cached-lfs-checkout@v1

#     - name: Ruff
#       uses: chartboost/ruff-action@v1